//! 各文件模板函数（模板字符串生成，无外部模板引擎）。

use crate::def::{DomainDef, FieldDef};

/// entity 文件模板：仿 sea-orm-cli 输出。
pub fn render_entity(def: &DomainDef) -> String {
    let fields = def
        .fields
        .iter()
        .map(render_entity_field)
        .collect::<Vec<_>>()
        .join("\n");
    format!(
        r#"//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "{table}")]
pub struct Model {{
{fields}
}}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {{}}

impl ActiveModelBehavior for ActiveModel {{}}
"#,
        table = def.table,
    )
}

fn render_entity_field(f: &FieldDef) -> String {
    let ty = crate::typing::entity_type(&f.rust_type);
    let comment = f
        .comment
        .as_ref()
        .map(|c| format!("    /// {c}\n"))
        .unwrap_or_default();
    if f.primary {
        if f.auto_increment {
            format!(
                "{comment}    #[sea_orm(primary_key, auto_increment = true)]\n    pub {}: {},",
                f.name, f.rust_type
            )
        } else {
            format!(
                "{comment}    #[sea_orm(primary_key)]\n    pub {}: {},",
                f.name, f.rust_type
            )
        }
    } else {
        format!("{comment}    pub {name}: {ty},", name = f.name, ty = ty)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::def::DomainDef;

    fn def() -> DomainDef {
        DomainDef::from_json(
            r#"{
                "domain": "dict", "table": "sys_dict", "comment": "数据字典",
                "fields": [
                    { "name": "id", "rust_type": "u64", "sql_type": "BIGINT UNSIGNED", "primary": true, "auto_increment": true },
                    { "name": "type_code", "rust_type": "String", "sql_type": "VARCHAR(64)", "unique": true },
                    { "name": "status", "rust_type": "i8", "sql_type": "TINYINT", "optional": true, "default": 1 },
                    { "name": "deleted_at", "rust_type": "Option<DateTime>", "sql_type": "DATETIME", "readonly": true, "soft_delete": true }
                ]
            }"#,
        )
        .unwrap()
    }

    #[test]
    fn entity_template_has_derive_and_columns() {
        let out = render_entity(&def());
        assert!(out.contains("DeriveEntityModel"));
        assert!(out.contains("#[sea_orm(table_name = \"sys_dict\")]"));
        assert!(out.contains("pub id: u64"));
        assert!(out.contains("pub type_code: String"));
        assert!(out.contains("pub deleted_at: Option<DateTime>"));
        assert!(out.contains("DeriveRelation"));
        assert!(out.contains("ActiveModelBehavior"));
    }
}
