//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_approval_record")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 审批实例 ID（hr_approval_instance.id）
    pub instance_id: u64,
    /// 节点顺序号（与模板 seq 对应）
    pub seq: i32,
    /// 节点名称快照
    pub node_name: String,
    /// 节点类型快照：1 直属上级 2 部门负责人 3 指定用户 4 指定角色
    pub node_type: i8,
    /// 解析出的审批人 sys_user.id；0=角色池（node_type=4）或解析不到
    pub approver_id: u64,
    /// 审批人引用 ID 快照（node_type=3 是 sys_user.id、=4 是 sys_role.id；角色池待办按它展开）
    pub approver_ref_id: u64,
    /// 动作：0 待审批 1 通过 2 驳回 3 跳过
    pub action: i8,
    /// 审批意见
    pub opinion: String,
    /// 动作时间
    pub acted_at: Option<DateTime>,
    /// 实际操作人 sys_user.id（角色池下与 approver_id 不同）
    pub acted_by: u64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
