//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_approval_flow")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 业务类型（字典 approvalBizType，如 timeOff / overtime；单列唯一含软删占位）
    pub biz_type: String,
    /// 模板名称
    pub name: String,
    /// 状态：1 启用 0 停用
    pub status: i8,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID（sys_user.id；0 表示种子/系统写入）
    pub created_by: u64,
    /// 更新人 ID（sys_user.id）
    pub updated_by: u64,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
