//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_attendance_record")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 员工档案 ID（hr_employee.id）
    pub employee_id: u64,
    /// 出勤日期（跨天班以班次开始日为准）
    pub work_date: Date,
    /// 班次 ID 快照（排班变更不改写历史事实）；0=当天休息
    pub shift_id: u64,
    /// 上班打卡时间
    pub clock_in: Option<DateTime>,
    /// 下班打卡时间
    pub clock_out: Option<DateTime>,
    /// 实际出勤分钟数
    pub actual_minutes: i32,
    /// 迟到分钟数
    pub late_minutes: i32,
    /// 早退分钟数
    pub early_leave_minutes: i32,
    /// 缺卡：0 无 1 缺上班卡 2 缺下班卡 3 上下班卡都缺
    pub miss_clock: i8,
    /// 数据来源：1 导入 2 手工补录 3 设备 4 钉钉 5 飞书
    pub source: i8,
    /// 第三方平台的记录 ID（配合 source 判重；本地补录为 None）
    pub external_id: Option<String>,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID（sys_user.id；0 表示系统写入）
    pub created_by: u64,
    /// 更新人 ID（sys_user.id）
    pub updated_by: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
