//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_approval_instance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 业务类型（字典 approvalBizType）
    pub biz_type: String,
    /// 业务单据 ID（软删主表 id；逻辑外键）
    pub biz_id: u64,
    /// 审批流模板 ID（提交时快照，模板后续改动不影响在途实例）
    pub flow_id: u64,
    /// 申请人 sys_user.id
    pub applicant_id: u64,
    /// 当前待审批节点顺序号；0=无可推进节点
    pub current_seq: i32,
    /// 当前节点审批人 sys_user.id；0=角色池或无（待办查询用）
    pub current_approver_id: u64,
    /// 当前节点角色池 sys_role.id；0=非角色池（待办查询用）
    pub current_approver_role_id: u64,
    /// 状态：1 审批中 2 已通过 3 已驳回 4 已撤销
    pub status: i8,
    /// 终态时间（2/3/4 时写入）
    pub finished_at: Option<DateTime>,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID（sys_user.id；0 表示系统写入）
    pub created_by: u64,
    /// 更新人 ID（sys_user.id）
    pub updated_by: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
