//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_approval_flow_node")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 审批流模板 ID（hr_approval_flow.id）
    pub flow_id: u64,
    /// 顺序号（从 1 递增，唯一键 (flow_id, seq)）
    pub seq: i32,
    /// 节点名称
    pub node_name: String,
    /// 节点类型：1 直属上级 2 部门负责人 3 指定用户 4 指定角色
    pub node_type: i8,
    /// 审批人引用 ID：node_type=3 时是 sys_user.id，=4 时是 sys_role.id，其余 0
    pub approver_ref_id: u64,
    /// 解析不到审批人时是否跳过：1 跳过 0 报错（最后一个节点必须为 0）
    pub skip_if_empty: i8,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID（sys_user.id；0 表示种子/系统写入）
    pub created_by: u64,
    /// 更新人 ID（sys_user.id）
    pub updated_by: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
