//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_employee")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 关联平台用户 ID（sys_user.id，逻辑外键，1:1）
    pub user_id: u64,
    /// 入职日期
    pub hire_date: Option<Date>,
    /// 转正日期；None 表示尚未转正
    pub regular_date: Option<Date>,
    /// 离职日期；None 表示在职
    pub leave_date: Option<Date>,
    /// 在职状态（字典 employmentStatus：1 在职、2 试用、3 离职）
    pub employment_status: i8,
    /// 最高学历（字典 education；0 未填）
    pub education: i8,
    /// 毕业院校
    pub graduate_school: String,
    /// 所学专业
    pub major: String,
    /// 身份证号（敏感字段，响应体脱敏）
    pub id_card: String,
    /// 紧急联系人
    pub emergency_contact: String,
    /// 紧急联系人电话
    pub emergency_phone: String,
    /// 工资卡号（敏感字段，响应体脱敏）
    pub bank_account: String,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID（sys_user.id；0 表示种子/系统写入）
    pub created_by: u64,
    /// 更新人 ID（sys_user.id）
    pub updated_by: u64,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
