//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_leave_type")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 类型编码（单列唯一，含软删占位）
    pub type_code: String,
    /// 类型名称
    pub type_name: String,
    /// 计量单位：1 天 2 小时
    pub unit: i8,
    /// 额度模式：1 扣额度 0 只记录不扣额度
    pub balance_mode: i8,
    /// 最小请假单位（分钟）：240=半天 480=一天
    pub min_unit_minutes: i32,
    /// 是否必须上传附件：1 是 0 否
    pub require_attachment: i8,
    /// 是否允许负余额：1 是 0 否
    pub allow_negative: i8,
    /// 计薪比例（千分比）：1000=全额 0=无薪（P5 使用）
    pub pay_ratio: i32,
    /// 状态：1 启用 0 停用
    pub status: i8,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID
    pub created_by: u64,
    /// 更新人 ID
    pub updated_by: u64,
    /// 软删除时间
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
