//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_shift")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 班次编码（单列唯一，含软删占位）
    pub shift_code: String,
    /// 班次名称
    pub shift_name: String,
    /// 上班时间（班次开始）
    pub start_time: Time,
    /// 下班时间（班次结束）
    pub end_time: Time,
    /// 是否跨天班：1 是（end_time 落在次日）0 否
    pub cross_day: i8,
    /// 应工作分钟数（已扣除休息）
    pub work_minutes: i32,
    /// 休息分钟数
    pub rest_minutes: i32,
    /// 迟到宽限分钟数
    pub late_tolerance_minutes: i32,
    /// 是否需要打卡：1 需要 0 不需要
    pub need_clock: i8,
    /// 状态：1 启用 0 停用
    pub status: i8,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID（sys_user.id；0 表示系统写入）
    pub created_by: u64,
    /// 更新人 ID（sys_user.id）
    pub updated_by: u64,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
