//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_time_off_request")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 员工档案 ID（hr_employee.id）
    pub employee_id: u64,
    /// 假期类型 ID（hr_time_off_type.id）
    pub time_off_type_id: u64,
    /// 请假开始时间
    pub start_at: DateTime,
    /// 请假结束时间
    pub end_at: DateTime,
    /// 请假分钟数（后端按排班 × 工作日历派生）
    pub duration_minutes: i32,
    /// 请假事由
    pub reason: String,
    /// 附件 ID（sys_file.id；0=无）
    pub attachment_id: u64,
    /// 状态：1 审批中 2 已通过 3 已驳回 4 已撤销
    pub status: i8,
    /// 审批实例 ID（hr_approval_instance.id；0=无）
    pub approval_instance_id: u64,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID（sys_user.id；0 表示系统写入）
    pub created_by: u64,
    /// 更新人 ID（sys_user.id）
    pub updated_by: u64,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
