//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_time_off_balance_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 账户 ID
    pub balance_id: u64,
    /// 员工档案 ID（冗余，便于按人查询）
    pub employee_id: u64,
    /// 假期类型 ID
    pub time_off_type_id: u64,
    /// 授予批次 ID；0=账户级操作
    pub grant_id: u64,
    /// 1 授予 2 手工调整 3 请假预占 4 审批实扣 5 驳回释放 6 过期作废
    pub biz_type: i8,
    /// 变动分钟数（正加负减）
    pub delta_minutes: i32,
    /// 变动前可用余额
    pub before_minutes: i32,
    /// 变动后可用余额
    pub after_minutes: i32,
    /// 0 无 1 系统任务 2 请假单 3 加班单 4 手工
    pub source_kind: i8,
    /// 来源对象 ID：`source_kind = 2 请假单` 时记**审批实例 ID**（= 一次提交周期，见
    /// `hr_time_off` service 的账本口径），`source_kind = 3 加班单` 时记加班单 ID，
    /// 其余（系统任务 / 手工）记 0 或批次 ID
    pub source_id: u64,
    /// 操作人 sys_user.id；0=系统
    pub operator_id: u64,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
