//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_time_off_balance")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 员工档案 ID（hr_employee.id）
    pub employee_id: u64,
    /// 假期类型 ID
    pub time_off_type_id: u64,
    /// 账期（自然年，如 2026）
    pub period: String,
    /// 累计授予
    pub granted_minutes: i32,
    /// 累计实扣
    pub used_minutes: i32,
    /// 审批中预占
    pub locked_minutes: i32,
    /// 累计失效作废
    pub expired_minutes: i32,
    /// 手工调整净额（可负）
    pub adjust_minutes: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID
    pub created_by: u64,
    /// 更新人 ID
    pub updated_by: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
