//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_time_off_grant")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 员工档案 ID（hr_employee.id）
    pub employee_id: u64,
    /// 假期类型 ID
    pub time_off_type_id: u64,
    /// 来源：1 发放 2 手工调整 3 加班转调休
    pub source: i8,
    /// 发放依据（字典 timeOffGrantReason）
    pub reason: String,
    /// 来源对象类型（与 `hr_time_off_balance_log.source_kind` 同口径）：0 无 1 系统任务 2 请假单 3 加班单 4 手工
    pub source_kind: i8,
    /// 来源对象 ID（配合 `source_kind` 作幂等键）：`2 请假单` 时是**审批实例 ID**
    /// （「归还批次」按一次提交周期一个桶），`3 加班单` 时是加班单 ID，其余为 0
    pub source_id: u64,
    /// 归属周期（如 2026）
    pub period: String,
    /// 授予分钟数（恒正）
    pub minutes: i32,
    /// 剩余可用分钟数
    pub remaining_minutes: i32,
    /// 生效日期
    pub effective_at: Date,
    /// 失效日期；None=永久有效
    pub expire_at: Option<Date>,
    /// 状态：1 有效 2 已用尽 3 已失效 4 已撤销
    pub status: i8,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID
    pub created_by: u64,
    /// 更新人 ID
    pub updated_by: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
