//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "hr_work_calendar")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 日期（单列唯一）
    pub calendar_date: Date,
    /// 是否工作日：1 是 0 否
    pub is_workday: i8,
    /// 日期类型：0 普通 1 法定节假日 2 调休上班
    pub holiday_type: i8,
    /// 该日标准工时（分钟）：无排班时的折算依据，默认 480
    pub standard_minutes: i32,
    /// 备注（如「国庆节」）
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID（sys_user.id；0 表示系统写入）
    pub created_by: u64,
    /// 更新人 ID（sys_user.id）
    pub updated_by: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
