//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

// 业务实体（HR）
pub mod hr_employee;
pub mod hr_time_off_balance;
pub mod hr_time_off_balance_log;
pub mod hr_time_off_grant;
pub mod hr_time_off_type;

pub mod sys_api;
pub mod sys_config;
pub mod sys_dept;
pub mod sys_dictionary;
pub mod sys_dictionary_detail;
pub mod sys_file;
pub mod sys_job;
pub mod sys_job_log;
pub mod sys_login_log;
pub mod sys_menu;
pub mod sys_operation_log;
pub mod sys_position;
pub mod sys_refresh_token;
pub mod sys_role;
pub mod sys_role_api;
pub mod sys_role_menu;
pub mod sys_site_config;
pub mod sys_user;
pub mod sys_user_dept;
pub mod sys_user_position;
pub mod sys_user_role;
