//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod sys_api;
pub mod sys_dictionary;
pub mod sys_dictionary_detail;
pub mod sys_file;
pub mod sys_login_log;
pub mod sys_menu;
pub mod sys_operation_log;
pub mod sys_role;
pub mod sys_role_api;
pub mod sys_role_menu;
pub mod sys_user;
pub mod sys_user_role;
