//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_login_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    /// 日志主键
    pub id: u64,
    /// 登录用户 ID（sys_user.id；失败为 0）
    pub user_id: u64,
    /// 本次登录尝试的用户名（超长截断 64 字符）
    pub username: String,
    /// 来源 IP
    pub ip: String,
    /// User-Agent（超长截断 255 字符）
    pub agent: String,
    /// 结果：1=成功，0=失败
    pub status: i8,
    /// 结果说明（失败原因或成功提示，如「密码错误」「登录成功」）
    pub msg: String,
    /// 创建时间
    pub created_at: DateTime,
    /// 软删除时间；NULL 表示未删除
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
