//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
//! W3 API 权限域实现前，Model / Relation 暂未被业务代码使用（dead_code 属预期）。
#![allow(dead_code)]

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_api")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub path: String,
    pub method: String,
    pub description: String,
    pub api_group: String,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
