//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
//!
//! 用户-部门挂载（多对多，硬删）。三个维度各管一件事，勿混：
//! - **一行** = 用户在某个部门的一次任职（可多行）；
//! - **`is_primary`** = 主要组织归属（展示 / 表单默认值 / 未来业务数据归属默认值），
//!   每用户**全局至多一个**（`validate` 保证 `depts` 非空时恰好一个 + DB 生成列唯一索引兜底），
//!   **不参与数据权限判定**；
//! - **`is_leader`** = 是否为该部门负责人，**可多个**（兼管多部门），
//!   是数据权限直控的凭据。

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_user_dept")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: u64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub dept_id: u64,
    /// 主部门：`1` 是 / `0` 否。
    ///
    /// 表达「主要组织归属」——用户列表显示哪个部门、表单默认选中哪个、
    /// 以及未来业务数据归属的默认值。每用户全局**至多一个** `1`
    /// （`validate` 保证 `depts` 非空时恰好一个，DB 生成列唯一索引兜底）；
    /// **不参与数据权限判定**（权限按全部挂载部门计算）。
    pub is_primary: i8,
    /// 本部门负责人位：`1` 是 / `0` 否；**可多个**（兼管多部门）。
    /// 与 `is_primary`（主部门归属）是两个独立维度，是数据权限直控的凭据。
    pub is_leader: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
