//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_menu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    pub parent_id: u64,
    pub path: String,
    pub name: String,
    pub component: String,
    pub title: String,
    pub icon: String,
    pub sort: i32,
    pub keep_alive: i8,
    pub hidden: i8,
    pub menu_type: i8,
    pub permission: String,
    pub status: i8,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
