//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_file")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 原始文件名（含扩展名，下载时用于 Content-Disposition）
    pub name: String,
    /// 磁盘存储名：<uuid>.<ext>（唯一，列表按此定位文件）
    pub stored_name: String,
    /// 小写扩展名（白名单校验依据）
    pub ext: String,
    /// Content-Type
    pub mime: String,
    /// 字节数
    pub size: u64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 上传人 ID
    pub created_by: u64,
    /// 更新人 ID
    pub updated_by: u64,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
