//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_dept")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u64,
    /// 父部门 ID，0 表示根部门
    pub parent_id: u64,
    /// 部门路径（段为祖先链到自身：根 `/0/{id}/`，子 `/0/父id/{id}/`）
    pub dept_path: String,
    pub dept_name: String,
    pub sort: i32,
    /// 状态：1 启用 / 0 停用
    pub status: i8,
    /// 同级互看：1 同部门普通成员可互看 / 0 关（默认）
    pub allow_peer_read: i8,
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID（sys_user.id；0 表示种子/系统写入）
    pub created_by: u64,
    /// 更新人 ID（sys_user.id）
    pub updated_by: u64,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
