//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_refresh_token")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    /// 登录刷新凭证记录主键
    pub id: u64,
    /// 登录用户 ID（sys_user.id）
    pub user_id: u64,
    /// 登录用户名（冗余快照，列表页免 join）
    pub username: String,
    /// refresh token 的 SHA-256 十六进制哈希（不存明文）
    pub refresh_token_hash: String,
    /// 登录 IP
    pub ip: String,
    /// 登录 User-Agent（超长截断 255 字符）
    pub agent: String,
    /// 最后活跃时间（60s 节流回写；5 分钟内视为在线）
    pub last_active_at: DateTime,
    /// 凭证过期时间（登录时刻 + jwt.refresh_ttl_seconds）
    pub expires_at: DateTime,
    /// 吊销时间；NULL 表示凭证有效
    pub revoked_at: Option<DateTime>,
    /// 吊销操作人（0=本人登出/系统，>0=管理员 user_id）
    pub revoked_by: u64,
    /// 吊销原因（用户登出/管理员强制下线）
    pub revoke_reason: String,
    /// 登录时间
    pub created_at: DateTime,
    /// 更新时间；MySQL 自动刷新
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    /// 会话归属用户（逻辑外键：user_id → sys_user.id，库内无物理 FK，与全库约定一致）。
    /// 供 `find_also_related` 单条 JOIN 取用户行，服务认证中间件的合并查询。
    #[sea_orm(
        belongs_to = "super::sys_user::Entity",
        from = "Column::UserId",
        to = "super::sys_user::Column::Id"
    )]
    User,
}

impl Related<super::sys_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
