//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_operation_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 操作人 ID
    pub user_id: u64,
    /// 来源 IP
    pub ip: String,
    /// 请求方法
    pub method: String,
    /// 请求路径
    pub path: String,
    /// HTTP 状态码
    pub status: i32,
    /// 请求耗时（毫秒）
    pub latency: i64,
    /// User-Agent
    pub agent: String,
    /// 请求体（脱敏截断后）
    #[sea_orm(column_type = "Text")]
    pub body: String,
    /// 响应体（脱敏截断后）
    #[sea_orm(column_type = "Text")]
    pub resp: String,
    /// 失败提示
    pub error_message: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
