//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_config")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 参数名称
    pub config_name: String,
    /// 参数键（业务内唯一，含软删占位）
    pub config_key: String,
    /// 参数值
    pub config_value: String,
    /// 备注
    pub remark: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    /// 创建人 ID
    pub created_by: u64,
    /// 更新人 ID
    pub updated_by: u64,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
