//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
//!
//! 用户-职位挂载（多对多，硬删）。一行 = 用户的一个任职职位（可多行，兼任场景）；
//! 职位不做「主职位」标记（对比 sys_user_dept.is_primary），多值纯展示。

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_user_position")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: u64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub position_id: u64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
