//! `SeaORM` Entity, generated by codegen

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_login_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u64,
    /// 登录成功后的用户 ID，失败为 0
    pub user_id: u64,
    /// 本次尝试的用户名
    pub username: String,
    /// 来源 IP
    pub ip: String,
    /// User-Agent
    pub agent: String,
    /// 1 成功 / 0 失败
    pub status: i8,
    /// 内部原因或成功提示
    pub msg: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
